// <auto-generated />
namespace ImpecMC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class wegzmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wegzmig));
        
        string IMigrationMetadata.Id
        {
            get { return "201504051107208_wegzmig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
