// <auto-generated />
namespace ImpecMC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class wgfag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wgfag));
        
        string IMigrationMetadata.Id
        {
            get { return "201504081511287_wgfag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
